### ISSUE TITLE
Does not work after .097>

### ISSUE THREAD

**Issue by immert20** [DavidMStraub/homeassistant-homeconnect#30] opened 2019-08-13 11:55 UTC
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/setup.py", line 172, in _async_setup_component
    component.setup, hass, processed_config  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/homeconnect/__init__.py", line 57, in setup
    simulate=config.get(DOMAIN, {}).get('simulate', False))
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 30, in __init__
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 69, in connect
    token = self.token_load()
  File "/usr/local/lib/python3.7/site-packages/homeconnect/api.py", line 50, in token_load
    token = json.load(f)
  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4258 (char 4257)

**Comment by DavidMStraub** [comment] 2019-08-13 12:27
Duplicate of #25.

**Closed by DavidMStraub** 2019-08-13 12:27 UTC
