### ISSUE TITLE
Sometimes its all unavailable

### ISSUE THREAD

**Issue by allmoney** [DavidMStraub/homeassistant-homeconnect#71] opened 2020-04-26 18:05 UTC
Sometimes all Home Connect devices in HA not update their statuses:

![image](https://user-images.githubusercontent.com/939594/80315635-94bd4c00-8801-11ea-892b-328542536a7a.png)

What can be wrong? Anybody can help?

**Comment by allmoney** [comment] 2020-04-26 18:07
Little time it send status< i rebooted HA and set Unavailable :(
Tried to reboot HA again - not helped...

![image](https://user-images.githubusercontent.com/939594/80315677-dfd75f00-8801-11ea-8fd8-3342d4b15e86.png)

**Comment by DavidMStraub** [comment] 2020-04-26 18:19
That can simply happen when your device is off.

**Comment by allmoney** [comment] 2020-04-26 18:23
Why? Why it not set to Off?

**Comment by DavidMStraub** [comment] 2020-05-02 08:29
Your screenshot shows the door state. There is no way to tell whether it's off (closed) when the device is offline. There is also no way of telling whether the device is actually off or the wifi is disabled. So "unavailable" is the correct status until the event stream reports something.

I believe this is not a bug but an API limitation, closing.

**Closed by DavidMStraub** 2020-05-02 08:29 UTC
