### ISSUE TITLE
Switched over to home_connect_beta but getting error 

### ISSUE THREAD

**Issue by julianrinaldi** [DavidMStraub/homeassistant-homeconnect#78] opened 2020-05-05 22:25 UTC
I removed the old integration and deleted everything. Reinstalled it with the proper directory name and updated the configuration. I added the integration and it seemed to have worked, although there were less entities than previously. However, the three entities that it now created all say unavailable, and on startup it says:

`The following integrations and platforms could not be set up:

home_connect_beta.binary_sensor
home_connect_beta.switch`

Am I missing something with the setup?

**Comment by DavidMStraub** [comment] 2020-05-06 07:00
Can you please look in the log? There should be an error traceback that will tell us where the problem is. Could be that a regression was introduced.

**Comment by k1rd3rf** [comment] 2020-05-06 07:46
I'm getting these as well: 

```
ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform home_connect_beta.binary_sensor: Platform not found (cannot import name 'BinarySensorEntity' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)).
ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform home_connect_beta.switch: Platform not found (cannot import name 'SwitchEntity' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)).
```

I'm getting the `duration`, `program_progress` and `remaining_program_time` sensors, and I'm using HA version 0.109.4.

**Comment by Krocko** [comment] 2020-05-06 10:28
Same for me

**Comment by k1rd3rf** [comment] 2020-05-06 10:57
Looks like there is a conflict in versions of HA due to i.e. https://github.com/home-assistant/core/commit/066e921a8b6f5264de4a93f604aed789c9730b73.

**Comment by DavidMStraub** [comment] 2020-05-06 11:46
Oooh. I hadn't noticed that these are not part of the released version yet. OK so I should roll this back at least for the beta component...

**Comment by DavidMStraub** [comment] 2020-05-06 16:00
I believe this is fixed now (on master), let me know if not.

**Closed** 2020-05-06 15:59 UTC
Labels: bug

**Comment by SeraphimSerapis** [comment] 2020-05-06 17:42
I installed 1.0 and still run into this issue:

```
Log Details (ERROR)
Logger: homeassistant.setup
Source: setup.py:249
First occurred: 7:40:29 PM (2 occurrences)
Last logged: 7:40:36 PM

Unable to prepare setup for platform home_connect_beta.switch: Platform not found (cannot import name 'SwitchEntity' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)).
Unable to prepare setup for platform home_connect_beta.binary_sensor: Platform not found (cannot import name 'BinarySensorEntity' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)).
```

**Comment by SeraphimSerapis** [comment] 2020-05-06 17:44
@DavidMStraub would you be able to release a new version? That should fix the issue for us!

**Comment by SeraphimSerapis** [comment] 2020-05-06 17:48
I can confirm this is fixed on master!

**Comment by Krocko** [comment] 2020-05-06 18:25
I can it confirm also.
But are there no more attributes under the Power Switch?

**Comment by DavidMStraub** [comment] 2020-05-06 18:51
No, see 1.0 release notes.

**Comment by Krocko** [comment] 2020-05-06 18:58
Ah ok. Thank you for clarification. 
I thought it was only removed in the core integration and not in the beta.
