### ISSUE TITLE
home connect integration stopped working after some time

### ISSUE THREAD

**Issue by FlavorFx** [DavidMStraub/homeassistant-homeconnect#64] opened 2020-03-08 11:27 UTC
Using home connect with my washing machine the integration stopped after around 1 hour. There war no update of the entities any more. 

BTW: There is an integration from cotwild that may be interesting for you as well: https://github.com/cotwild/home_connect. May be it make sense to combine activities.

<img width="400" alt="Bildschirmfoto 2020-03-07 um 19 22 54" src="https://user-images.githubusercontent.com/19329488/76161679-ecaad100-6135-11ea-9680-ba10d7e3912d.png">

<img width="400" alt="Bildschirmfoto 2020-03-07 um 19 22 54" src="https://user-images.githubusercontent.com/19329488/76161714-3398c680-6136-11ea-8040-aaf4b9a97788.png">

**Comment by DavidMStraub** [comment] 2020-03-08 19:13
Hi, please follow this issue: 
https://github.com/DavidMStraub/homeconnect/issues/3

But please note that I will need the logs (with debug logging) to get anything useful.

Closing as duplicate of https://github.com/DavidMStraub/homeconnect/issues/3.

**Closed by DavidMStraub** 2020-03-08 19:13 UTC
