### ISSUE TITLE
Integration not Found after last upgrade

### ISSUE THREAD

**Issue by naked-head** [DavidMStraub/homeassistant-homeconnect#81] opened 2020-05-06 10:40 UTC
After last upgrade I got many error, I upgrade homeassistant and after reboot I got this error:

> ERROR (MainThread) [homeassistant.setup] Setup failed for homeconnect: Integration not found.

so I performed uninstall under HACS, restart and after that I can find homeconnect again in my integration list but device and entity list say that are all unavailable. I try deleting related configuration in configuration.yaml, but I got the same error. So I try install the beta version and now in my integration List I got "homeconnect" and "Home Connect" but the error still remain and I got two new error, this is what notification say:

> The following integrations and platforms could not be set up:
>     homeconnect
>     home_connect_beta.binary_sensor
>     home_connect_beta.switch
> Please check your config.

What can I do to solve?
thanks

**Comment by DavidMStraub** [comment] 2020-05-06 11:47
Duplicate of #78. Please check existing issues.

**Closed by DavidMStraub** 2020-05-06 11:47 UTC
