### ISSUE TITLE
OAuth 2 MUST utilize https

### ISSUE THREAD

**Issue by deuntje** [DavidMStraub/homeassistant-homeconnect#11] opened 2019-01-09 20:53 UTC
I'm trying to link my Home Connect account, but get this 500 Internal Server Error on the callback after I approved my application to access my account:

500 Internal Server Error
Server got itself in trouble

The callback URL censored) : https://smarthome.xxxxxxxxxxxxxxxxxxx.xxx/api/homeconnect?code=eyJ4XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx&state=rBzaXXXXXXXXXXXXXXXXXXXXXXXXx&grant_type=authorization_code

In my homeassistant.log I see this error:

```
2019-01-09 20:57:47 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/opt/homeassistant/lib/python3.5/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/static.py", line 66, in staticresource_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/real_ip.py", line 34, in real_ip_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/ban.py", line 67, in ban_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/auth.py", line 99, in auth_middleware
    return await handler(request)
  File "/opt/homeassistant/lib/python3.5/site-packages/homeassistant/components/http/view.py", line 118, in handle
    result = await result
  File "/home/homeassistant/.homeassistant/custom_components/homeconnect/__init__.py", line 123, in get
    hass.async_add_job(
  File "/opt/homeassistant/lib/python3.5/site-packages/homeconnect/api.py", line 95, in get_token
    client_secret=self.client_secret)
  File "/opt/homeassistant/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 187, in fetch_token
    state=self._state)
  File "/opt/homeassistant/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/web_application.py", line 174, in parse_request_uri_response
    response = parse_authorization_code_response(uri, state=state)
  File "/opt/homeassistant/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 221, in parse_authorization_code_response
    raise InsecureTransportError()
oauthlib.oauth2.rfc6749.errors.InsecureTransportError: (insecure_transport) OAuth 2 MUST utilize https.
```

I use a nginx reverse proxy with let's encrypt for the https, I also have the base_url in my HA-config. I've checked the browser communication with the developer tools and saw that all of the communication was over https. 

Any tips  to get my Home Connect linked or any clue why this error occurs?

Thanks in advance!
Dennis

**Comment by DavidMStraub** [comment] 2019-01-10 07:12
Hi,

could this be a duplicate of #3? I still haven't inserted the [solution](https://github.com/DavidMStraub/homeassistant-homeconnect/issues/3#issuecomment-444008496) into the code by default.

**Comment by deuntje** [comment] 2019-01-10 09:23
I saw this issue, also tried it but in that point of time I did not restart HA after the change (reverted the change because I thought it was not effective). 

Now I've retested it and restarted HA after the change, now my Home Connect account is linked and my washing machine is in HA 👍  

Sorry for the duplicate issue.

**Closed** 2019-01-10 09:34 UTC
