### ISSUE TITLE
missing status for dishwasher

### ISSUE THREAD

**Issue by Heiner1967** [DavidMStraub/homeassistant-homeconnect#56] opened 2020-01-28 18:53 UTC
Hi, 

many Thanks first of all for this integration.

Homeaconnect show further status messages but the integration not yet. 
Things like 
the salt comes to a end, or 
the rinse aid, or
that I shall use the mashine cleaning program.

Would be great if this could be added.

**Comment by DavidMStraub** [comment] 2020-01-28 21:50
Since these are events, I believe this is a duplicate of #42.

**Comment by DavidMStraub** [comment] 2020-05-05 19:07
Closing as duplicate.

**Closed by DavidMStraub** 2020-05-05 19:07 UTC
