### ISSUE TITLE
unauthorized_client - External URL

### ISSUE THREAD

**Issue by allmoney** [DavidMStraub/homeassistant-homeconnect#95] opened 2020-07-02 15:36 UTC
Now at https://xxx.duckdns.org:8123/config/core
We have External URL and Internal URL.
I have filled only External URL.
When I click "Open Website" I got error:
![image](https://user-images.githubusercontent.com/939594/86378687-9c322300-bc92-11ea-9dd7-0b244607b256.png)
{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "xxx"
}

I see incorrect internal URL in opened page:
https://api.home-connect.com/security/oauth/authorize?response_type=code&client_id=111&redirect_uri=**https://192.168.1.52**:8123/auth/external/callback&state=2.3

It must be **External URL**.

**Comment by DavidMStraub** [comment] 2020-07-02 17:08
Duplicate of https://github.com/home-assistant/core/issues/35844.

Please use issues in this repo only for things related to beta features that are not in core.

**Closed by DavidMStraub** 2020-07-02 17:08 UTC
