### ISSUE TITLE
Oven programs don't start

### ISSUE THREAD

**Issue by janbernhardt** [DavidMStraub/homeassistant-homeconnect#50] opened 2020-01-09 17:16 UTC
Finally I was able to connect my oven with this integration. Great work, thank you very much!

I can see valid sensor values and the general turn on/off switch for the oven is working fine.
However if I try to select on of the program switches I don't see any response on my device.
I would also expect that I need to set a temperature which I could not see anywhere.

**Comment by janbernhardt** [comment] 2020-01-09 18:05
Investigating a little bit more on this, it looks like that the homeconnect API currently does not provide any "options" to be set along with the program name.
https://developer.home-connect.com/docs/oven/supported_programs_and_options

**Comment by janbernhardt** [comment] 2020-01-09 19:25
I'm wondering if it makes more sense to have a service interface to start specific programs (including temperature and duration) instead of switches.

**Comment by DavidMStraub** [comment] 2020-01-10 06:46
I think that's a duplicate of #13.

Concerning your last comment, I agree; that's the gist of #23, on which I haven't had time to work though (but would be grateful about help).

**Comment by SeraphimSerapis** [comment] 2020-01-23 08:05
I ran into a similar issue with my coffee machine, where the switch for coffee or espresso seems to start the process (the machine indicates a selected program and starts grinding beans) but comes to a hold before dispensing the coffee.

**Comment by DavidMStraub** [comment] 2020-05-05 19:12
Closing as duplicate of #13 and #23 (not sure about the coffee machine, might be a separate issue).

**Closed by DavidMStraub** 2020-05-05 19:12 UTC
