### ISSUE TITLE
Washdryer - washing programs and drying programs have the same name

### ISSUE THREAD

**Issue by Krocko** [DavidMStraub/homeassistant-homeconnect#119] opened 2020-12-01 19:53 UTC
I have a Siemens washdryer (WD14U592)
The integration generates the same names for the washing programs and the drying programs. 
I get the following error and no drying programs are added. 
```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:490 
Integration: Schalter (documentation, issues) 
First occurred: 20:26:39 (4 occurrences) 
Last logged: 20:26:39

Platform home_connect_beta does not generate unique IDs. ID SIEMENS-WD14U592-68A40E36D132-Program Cotton already exists - ignoring switch.waschmaschine_program_cotton
Platform home_connect_beta does not generate unique IDs. ID SIEMENS-WD14U592-68A40E36D132-Program Mix already exists - ignoring switch.waschmaschine_program_mix
Platform home_connect_beta does not generate unique IDs. ID SIEMENS-WD14U592-68A40E36D132-Program Outdoor already exists - ignoring switch.waschmaschine_program_outdoor
Platform home_connect_beta does not generate unique IDs. ID SIEMENS-WD14U592-68A40E36D132-Program Towels already exists - ignoring switch.waschmaschine_program_towels
```

**Comment by Krocko** [comment] 2020-12-02 11:03
@yusijs Have you the same problem?

**Comment by yusijs** [comment] 2020-12-02 17:39
Yes, sort of; the problem is that HomeConnect doesnt expose the programs separately. I noticed it in my logs and was thinking of looking at resolving it, but I rarely, if ever use those toggles, so I couldnt be bothered

**Comment by Krocko** [comment] 2020-12-02 17:50
Maybe in the homebridge repository is something useful?

https://github.com/thoukydides/homebridge-homeconnect

**Comment by DavidMStraub** [comment] 2021-05-07 17:57
Sorry I never reacted to this. This is caused by this line

```python
desc = " ".join(["Program", program_name.split(".")[-1]])
```

Only the last part of the program is used for the unique ID. Removing `.split(".")[-1]` should fix it. Do you want to submit a PR?

**Comment by DavidMStraub** [comment] 2021-05-07 17:57
Ideally, after testing it since I don't have a WasherDryer :)

**Comment by yusijs** [comment] 2021-05-09 09:38
I'll give it a spin! :)

**Comment by yusijs** [comment] 2021-05-09 10:00
@DavidMStraub I just got a weird, new error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/home_connect_beta/__init__.py", line 222, in async_setup_entry
    hass.config_entries.async_setup_platform(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platform'
```

Any clue as to where I should look to solve this?

**Comment by DavidMStraub** [comment] 2021-05-09 18:50
Are you sure you are using the latest version from `master`? The line looks different:

https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/home_connect_beta/__init__.py#L222

**Comment by yusijs** [comment] 2021-05-10 05:43
I am, and it is identical `hass.config_entries.async_setup_platform(entry, PLATFORMS)`

**Closed** 2021-05-10 18:04 UTC
Labels: bug
