### ISSUE TITLE
Component doesn't work reliable

### ISSUE THREAD

**Issue by h4nc** [DavidMStraub/homeassistant-homeconnect#65] opened 2020-03-11 13:37 UTC
I noticed that the component doesn't work reliable for me. I use it with a Siemens oven. For me it seems like it works sometimes but most times it doesn't. Meaning that the entities don't get an update. 
For example I have a Lovelace card that shows up on my main page when the oven is on. The thing is that it sometimes when the oven in on it doesn't show as on in home assistant. 

Did not notice an error yet and before I dig in more into this, I'd like to know if this is a known issue. I know this would be something in a forum thread, but I'm afraid it wouldn't reach you @DavidMStraub 

Not sure but I think when I restart ha during the oven is on, I will get those updates (same as for the internal temperature, but I already know about that issue and it can't be addressed currently).

**Comment by DavidMStraub** [comment] 2020-03-11 19:42
Looks like another duplicate of https://github.com/DavidMStraub/homeconnect/issues/3.

**Closed by DavidMStraub** 2020-03-11 19:42 UTC
