### ISSUE TITLE
"unauthorized_client"

### ISSUE THREAD

**Issue by qwt2003** [DavidMStraub/homeassistant-homeconnect#52] opened 2020-01-13 06:52 UTC
Hi, I have to say, this is an excellent work. But I still got some problems.

When I followed the guide install this plug-in and reset the HA service, I got a error:
{
  "error": "unauthorized_client",
  "error_description": "client or redirection URI not authorized",
  "state": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmbG93X2lkIjoiZmIwOTEzYzMwYjE3NGQyYjg2ZjZkMzQ3ZTIxNjdhYjUifQ.aidwZ7ZCaOVAODfL3FRygYna-xQfEuwh_iflteVhzoA"
}
Is this mean I need to verify my application in HomeConnectDev?

BTW, my application's OAuth Flow is Authorization Code Grant Flow.

**Comment by DavidMStraub** [comment] 2020-01-13 07:50
Maybe you didn't set the `base_url` in HA config or not the correct Redirect URI in Home Connect.

**Comment by Jaykurb** [comment] 2020-01-15 23:16
Everything used to work but it was effected by the breaking changes. I'm getting the same issue and pretty sure everything is set correctly. 

config.yaml

```
http:
   base_url: MYIPADDY:8123
```


Redirect URI
`https://MYIPADDY.8123/auth/external/callback`

**Comment by qwt2003** [comment] 2020-01-15 23:34
> Everything used to work but it was effected by the breaking changes. I'm getting the same issue and pretty sure everything is set correctly.
> 
> config.yaml
> 
> ```
> http:
>    base_url: MYIPADDY:8123
> ```
> 
> Redirect URI
> `https://MYIPADDY.8123/auth/external/callback`

I think I found the solution, according to @gkreitz HA integration BOSCH dryer program, we need to verify the HomeConnect Dev APP by end user and the application’s OAuth should use Device Flow. 

But I can’t try this method because my homeconnect ID is a Chinese cellphone number and email login HomeConnect in China is unavailable since 2018.

**Comment by DavidMStraub** [comment] 2020-01-16 05:53
Add `https://` to the `base_url`. The Redirect URI has a dot instead of a colon. Which "breaking changes"?

**Comment by Jaykurb** [comment] 2020-01-16 11:05
I have added https:// to the base_url and swapped the dot for a colon, this has stopped the invalid config error but the entities are not showing in HA. I assumed it stopped working because of these breaking changes https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/README.md#recent-breaking-changes

**Comment by DavidMStraub** [comment] 2020-01-16 19:15
> Should we need to redirect local IP to a public IP via FRP

This is answered in the Readme. Please read it.

**Comment by qwt2003** [comment] 2020-01-20 07:36
> > Should we need to redirect local IP to a public IP via FRP
> 
> This is answered in the Readme. Please read it.

Well, after I redirect the loacl IP to the public, it's still report the same error. I think I should find a way to verify home-connect dev application. I'm in China and my home-connect end user account's name is a cellphone number, I can't pass the verify step via cellphone number.

**Comment by DavidMStraub** [comment] 2020-01-20 07:53
Interesting, then that might be the problem. Please ask the Home Connect support, they are usually quite responsive.

**Comment by emergentjlr** [comment] 2020-02-14 16:05
I am having the same issue.

My base_url is set to "https://homeassistant.mydomain.com:80"

My URI is set to "https://homeassistant.mydomain.com:80/auth/external/callback"

When I try to add the integration I get the same error as above.

**Comment by andre68723** [comment] 2020-05-02 21:09
my issue is a bit different, setup with nginx and a duckdns domain
```
 http:
   base_url: https://foo.duckdns.org:443
```

BSH-Portal Redirect URI
`https://foo.duckdns.org:443/auth/external/callback`


the url generated when adding the integration is containing the local ip (http with s) **192.168.0.3** of HA and not the foo.duckdns.org expected

https://api.home-connect.com/security/oauth/authorize?response_type=code&client_id=bar&redirect_uri=http://192.168.0.3:8123/auth/external/callback&state=bar

anything I missed?

**Comment by DavidMStraub** [comment] 2020-05-05 19:10
Can you please double-check die BSH portal redirect URI? The Home Connect auth form has to get that 192. address from *somewhere*...

**Comment by andre68723** [comment] 2020-05-05 19:59
agreed, but somehow I suspect the NGINX setup. Did you test the addon in a similar setup?

Some pics, 

![Bildschirmfoto 2020-05-05 um 21 54 10](https://user-images.githubusercontent.com/16468234/81110099-5ddee880-8f1b-11ea-8329-6f2457e47861.png)
![Bildschirmfoto 2020-05-05 um 21 55 12](https://user-images.githubusercontent.com/16468234/81110114-659e8d00-8f1b-11ea-9d18-142671c23637.png)

**Comment by Mats80L** [comment] 2020-05-15 08:50
I am also using nginx and have the exact same problem
Also seeing a local IP in the error message

**Comment by DavidMStraub** [comment] 2020-05-15 10:08
Thinking about it again, I think the problem is not on the Home Connect side: it is Home Assistant that is calling the authorize endpoint with the wrong redirect URI appended. But this is very surprising. Somehow it seems your `base_url` setting is ignored. Anyway, I don't think it is a bug of this integration.

**Comment by DavidMStraub** [comment] 2020-05-15 10:09
@andre68723, in the screenshot you posted it looks like there is one space too much in front of `http`. Maybe just a YAML formatting problem?

**Comment by andre68723** [comment] 2020-05-15 12:01
> Thinking about it again, I think the problem is not on the Home Connect side: it is Home Assistant that is calling the authorize endpoint with the wrong redirect URI appended. But this is very surprising. Somehow it seems your `base_url` setting is ignored. Anyway, I don't think it is a bug of this integration.

this here https://github.com/home-assistant/home-assistant.io/pull/13307 looks to me as if the setting has become obsolete

PS: its just one space, checked

**Comment by andre68723** [comment] 2020-05-22 10:45
workaround with 0.110+ and same ext+int url:
```
homeassistant:
  external_url: "https://abcd.duckdns.org"
  internal_url: "https://abc.duckdns.org"
```
+ removal of the 443 from the home conect Redirect URIs, must be exactly matching
`https://abc.duckdns.org/auth/external/callback`

still a bug somewhere

**Comment by DavidMStraub** [comment] 2020-05-22 14:19
I can't follow. Are you saying that you need to set the `internal_url` to the same value as `external_url`?

**Comment by andre68723** [comment] 2020-05-22 14:27
Yes, as in https://github.com/DavidMStraub/homeassistant-homeconnect/issues/84

**Comment by DavidMStraub** [comment] 2020-05-22 14:33
So what's the bug? I still don't get it. Also, you seem to have a typo above (abc vs abcd, or is that intentional?)

**Comment by andre68723** [comment] 2020-05-22 14:53
Bug:  Having to use the external_url as internal_url in order to setup the integration properly

**Comment by DavidMStraub** [comment] 2020-05-22 15:28
If this is the case, it's a Home Assistant Core bug. Authorization is handled by core.

**Comment by DavidMStraub** [comment] 2020-05-22 15:30
Closing as duplicate of https://github.com/home-assistant/core/issues/35844.

**Closed by DavidMStraub** 2020-05-22 15:30 UTC

**Comment by linjt325** [comment] 2022-10-11 08:36
> > > Should we need to redirect local IP to a public IP via FRP
> > 
> > 
> > This is answered in the Readme. Please read it.
> 
> Well, after I redirect the loacl IP to the public, it's still report the same error. I think I should find a way to verify home-connect dev application. I'm in China and my home-connect end user account's name is a cellphone number, I can't pass the verify step via cellphone number.

在中国应用商城下载的home connect好像是连到国内的服务器上 用的域名是home-connect.cn  两边数据不互通。我最近也碰到这个问题 不知道是否已经解决
