### ISSUE TITLE
Problem with 0.115 and 0.116

### ISSUE THREAD

**Issue by skaker1** [DavidMStraub/homeassistant-homeconnect#111] opened 2020-10-08 11:15 UTC
Get this after upgrading to 0.116:

Home Connect has stopped working. Component error: home_connect_beta - cannot import name ‘UNIT_PERCENTAGE’ from ‘homeassistant.const’ (/usr/src/homeassistant/homeassistant/const.py)

It was changed since 0.115 according to the developers.

**Comment by DavidMStraub** [comment] 2020-10-08 11:33
Another duplicate of #106.

**Closed by DavidMStraub** 2020-10-08 11:33 UTC
