### ISSUE TITLE
UNIT PERCENTAGE

### ISSUE THREAD

**Issue by t0bse** [DavidMStraub/homeassistant-homeconnect#110] opened 2020-10-05 11:29 UTC
The UNIT_PERCENTAGE constant was changed to PERCENTAGE since 0.115 this causes an error:

Component error: home_connect_beta - cannot import name 'UNIT_PERCENTAGE' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

could you please fix this? :)

**Comment by DavidMStraub** [comment] 2020-10-05 11:38
Duplicate of #106.

**Closed by DavidMStraub** 2020-10-05 11:38 UTC
