### ISSUE TITLE
Feature request: binary sensor to show if remote start is enabled or not.

### ISSUE THREAD

**Issue by em0g** [DavidMStraub/homeassistant-homeconnect#103] opened 2020-08-10 21:28 UTC
Hi, it would be great if I had a binary sensor to show if remote start is enabled or not for the dishwasher. 

Thanks a bunch for the great work on this HA component

**Comment by DavidMStraub** [comment] 2020-08-11 16:14
Duplicate of #99.

**Closed by DavidMStraub** 2020-08-11 16:14 UTC
